export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_SUBCATEGORY = 'GET_SUBCATEGORY';
export const GET_CATEGORY_AND_SUBCATEGORY = 'GET_CATEGORY_AND_SUBCATEGORY';
export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT';
export const PRODUCT_INFO = 'PRODUCT_INFO';
